//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCS_Requests.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SCS_Functions", Namespace="http://schemas.datacontract.org/2004/07/SCSClassLibrary")]
    [System.SerializableAttribute()]
    public partial class SCS_Functions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet getbystockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet gettotalsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet getbystock {
            get {
                return this.getbystockField;
            }
            set {
                if ((object.ReferenceEquals(this.getbystockField, value) != true)) {
                    this.getbystockField = value;
                    this.RaisePropertyChanged("getbystock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet gettotals {
            get {
                return this.gettotalsField;
            }
            set {
                if ((object.ReferenceEquals(this.gettotalsField, value) != true)) {
                    this.gettotalsField = value;
                    this.RaisePropertyChanged("gettotals");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISCS_Service")]
    public interface ISCS_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCS_Service/gettotals", ReplyAction="http://tempuri.org/ISCS_Service/gettotalsResponse")]
        SCS_Requests.ServiceReference1.SCS_Functions gettotals(string keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCS_Service/gettotals", ReplyAction="http://tempuri.org/ISCS_Service/gettotalsResponse")]
        System.Threading.Tasks.Task<SCS_Requests.ServiceReference1.SCS_Functions> gettotalsAsync(string keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCS_Service/getbystock", ReplyAction="http://tempuri.org/ISCS_Service/getbystockResponse")]
        SCS_Requests.ServiceReference1.SCS_Functions getbystock(string stockref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCS_Service/getbystock", ReplyAction="http://tempuri.org/ISCS_Service/getbystockResponse")]
        System.Threading.Tasks.Task<SCS_Requests.ServiceReference1.SCS_Functions> getbystockAsync(string stockref);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISCS_ServiceChannel : SCS_Requests.ServiceReference1.ISCS_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SCS_ServiceClient : System.ServiceModel.ClientBase<SCS_Requests.ServiceReference1.ISCS_Service>, SCS_Requests.ServiceReference1.ISCS_Service {
        
        public SCS_ServiceClient() {
        }
        
        public SCS_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCS_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCS_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCS_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SCS_Requests.ServiceReference1.SCS_Functions gettotals(string keys) {
            return base.Channel.gettotals(keys);
        }
        
        public System.Threading.Tasks.Task<SCS_Requests.ServiceReference1.SCS_Functions> gettotalsAsync(string keys) {
            return base.Channel.gettotalsAsync(keys);
        }
        
        public SCS_Requests.ServiceReference1.SCS_Functions getbystock(string stockref) {
            return base.Channel.getbystock(stockref);
        }
        
        public System.Threading.Tasks.Task<SCS_Requests.ServiceReference1.SCS_Functions> getbystockAsync(string stockref) {
            return base.Channel.getbystockAsync(stockref);
        }
    }
}
